version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: moodle
    image: moodle
    depends_on:
      - db
    environment:
      #Cambiar por la url de su servidor
      MOODLE_URL: http://localhost
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - moodle_data:/var/moodledata

  db:
    build: ./databases
    container_name: DB
    image:  mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db_data:/var/lib/mysql

volumes:
  my-db_data:
    driver: local
  moodle_data:
    driver: local